Repository ryceg/Eigengrau-s-Essential-Establishment-Generator, pull requests merged in 2020-12, with the labels that each got.

#415 Fix Weather Bug
  lib/src/terrain.ts
  lib/src/weather.ts
  lib/town/_common.ts
  src/Town/Weather/js/createWeather.js
  src/Town/Weather/js/renderWeather.js
  src/setup.d.ts
Labels: bug, enhancement

#442 Update dependencies
  package.json
  yarn.lock
Labels: dependencies

#444 Remove deprecated eslint-plugin-standard package
  lib/npc-generation/createReligiosity.ts
  package.json
  yarn.lock
Labels: dependencies

#456 Migrate to typescript
  .github/workflows/continous_integration.yml
  .github/workflows/release.yml
  global.d.ts
  lib/index.ts
  lib/npc-generation/_common.ts
  lib/npc-generation/createLifestyleStandards.ts
  lib/npc-generation/familyRaces.ts
  lib/town/_common.ts
  scripts/rollup.config.js
  src/NPCGeneration/Relationships/FamilyData.js
  src/NPCGeneration/Relationships/FamilySurnames.js
  src/NPCGeneration/Relationships/createFamilyMembers.d.ts
  src/NPCGeneration/Relationships/createFamilyMembers.js
  src/NPCGeneration/Relationships/createFamilyMembers.ts
  src/NPCGeneration/Relationships/createFriends.d.ts
  src/NPCGeneration/Relationships/createFriends.ts
  src/NPCGeneration/Relationships/familyUtils.ts
  src/NPCGeneration/Relationships/getFatherMother.ts
  src/NPCGeneration/Relationships/getSurnames.ts
  src/NPCGeneration/Relationships/setAsPartners.d.ts
  src/NPCGeneration/Relationships/setAsPartners.ts
  src/main.ts
  src/setup.d.ts
  sugarcube.d.ts
  tsconfig.json
Labels: enhancement

#461 Convert createRelationship to TypeScript
  src/NPCGeneration/Relationships/createFriends.ts
  src/NPCGeneration/Relationships/createRelationship.d.ts
  src/NPCGeneration/Relationships/createRelationship.ts
  src/NPCGeneration/Relationships/familyUtils.ts
  src/main.ts
Labels: TypeScript, enhancement

#462 Convert createSexuality to TS
  lib/npc-generation/_common.ts
  src/NPCGeneration/Relationships/SetupSexuality.js
  src/NPCGeneration/Relationships/createFriends.ts
  src/NPCGeneration/Relationships/createSexuality.ts
  src/main.ts
Labels: TypeScript, enhancement

#465 Convert createDebt to TS
  src/NPCGeneration/Relationships/createFriends.ts
  src/NPCGeneration/Relationships/getFamily.ts
  src/NPCGeneration/createDebt.d.ts
  src/NPCGeneration/createDebt.ts
  src/main.ts
Labels: TypeScript, enhancement

#469 Convert delete npc to ts
  lib/src/utils.ts
  src/NPCGeneration/deleteNPC.d.ts
  src/NPCGeneration/deleteNPC.ts
  src/main.ts
Labels: TypeScript, enhancement

#468 Reenable source maps
  scripts/rollup.config.js
Labels: enhancement

#473 Update @typescript-eslint
  package.json
  yarn.lock
Labels: dependencies

#474 Convert deleteBuilding to TS
  src/Buildings/deleteBuilding.d.ts
  src/Buildings/deleteBuilding.js
  src/Buildings/deleteBuilding.ts
  src/main.ts
Labels: TypeScript, enhancement
